language: generic
sudo: required
services:
  - docker

before_install: 
  - docker build -t gidonco/docker-react -f Dockerfile.dev .

script: 
  - docker run -e CI=true gidonco/docker-react npm run test -- --coverage