language: generic
sudo: required
services:
  - docker

before_install: 
  - docker build -t gidonco/docker-react -f Dockerfile.dev .

script: 
  - docker run -e CI=true gidonco/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "eu-cental-1"
  app: "docker-react"
  env: "Dockerreact-env"
  bucket_name: elasticbeanstalk-eu-central-1-873655438342
  on:
    branch: master
  access_key_id: 
    secure: $AWS_ACCESS_KEY
  secret_access_key: 
    secure: "$AWS_SECRET_KEY"