version: '3.8'
services:
  web:
    build: 
      context: .
      dockerfile: Dockerfiqle.dev
    ports:
    - 3000:3000
    volumes:
      - /home/node/app/node_modules
      - .:/home/node/app
  tests:
      build: 
        context: .
        dockerfile: Dockerfiqle.dev
      volumes:
        - /home/node/app/node_modules
        - .:/home/node/app
      command: ["npm", "run", "test"]